/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,jsx}'],
    theme: {
        extend: {
            colors: {
                background: '#fff8f6',
                surface: '#ffffff',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#fff1ec',
                'surface-container': '#ffe9e3',
                'surface-container-high': '#fae4dd',
                'surface-container-highest': '#f4ded7',
                'surface-variant': '#f4ded7',
                'surface-dim': '#ebd6cf',
                'surface-bright': '#fff8f6',
                primary: '#a43c12',
                'primary-container': '#ff7f50',
                'primary-fixed': '#ffdbcf',
                'primary-fixed-dim': '#ffb59c',
                secondary: '#006a65',
                'secondary-container': '#76f3ea',
                'secondary-fixed': '#79f6ed',
                'secondary-fixed-dim': '#59dad1',
                tertiary: '#8d4f11',
                'tertiary-container': '#df9350',
                'tertiary-fixed': '#ffdcc3',
                'tertiary-fixed-dim': '#ffb77d',
                error: '#ba1a1a',
                'error-container': '#ffdad6',
                outline: '#8b7169',
                'outline-variant': '#dec0b6',
                'on-background': '#241915',
                'on-surface': '#241915',
                'on-surface-variant': '#57423b',
                'on-primary': '#ffffff',
                'on-primary-container': '#6c2000',
                'on-primary-fixed': '#380c00',
                'on-primary-fixed-variant': '#822800',
                'on-secondary': '#ffffff',
                'on-secondary-container': '#006f69',
                'on-secondary-fixed': '#00201e',
                'on-secondary-fixed-variant': '#00504c',
                'on-tertiary': '#ffffff',
                'on-tertiary-container': '#5b2f00',
                'on-tertiary-fixed': '#2f1500',
                'on-tertiary-fixed-variant': '#6e3900',
                'on-error': '#ffffff',
                'on-error-container': '#93000a',
                'inverse-surface': '#3a2e29',
                'inverse-on-surface': '#ffede8',
                'inverse-primary': '#ffb59c',
                'surface-tint': '#a43c12',
                blue: {
                    DEFAULT: '#2563EB',
                    50: '#EFF6FF',
                    100: '#DBEAFE',
                    500: '#3B82F6',
                    600: '#2563EB',
                    700: '#1D4ED8',
                },
                teal: {
                    DEFAULT: '#14B8A6',
                    50: '#F0FDFA',
                    100: '#CCFBF1',
                    500: '#14B8A6',
                    600: '#0D9488',
                },
                amber: {
                    DEFAULT: '#F59E0B',
                    50: '#FFFBEB',
                    500: '#F59E0B',
                },
            },
            fontFamily: {
                sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
            },
        },
    },
    plugins: [],
};